# -*- coding: utf-8 -*-
"""Anagram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w3U8Lf3f4e9vJWzOq_643SRcPV88KlXZ

What is an anagram? Well, two words are anagrams of each other if they both contain the same letters. For example:

'abba' & 'baab' == true

'abba' & 'bbaa' == true

'abba' & 'abbba' == false

'abba' & 'abca' == false
Write a function that will find all the anagrams of a word from a list. You will be given two inputs a word and an array with words. You should return an array of all the anagrams or an empty array if there are none.
"""

anagram_list =[]
def anagrams(a,b):
  for i in b:
    if sorted(a)==sorted(i):
      
      anagram_list.append(i)
    else:
      continue
  return anagram_list

anagrams('abba', ['aabb', 'abcd', 'bbaa', 'dada'])