# -*- coding: utf-8 -*-
"""basamak_sayısı.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AOh5qlj-swDq27P2IuUCr07EBZzCyW89
"""

def digits(n):
  basamak=len(str(n))
  sonuc=0
  for i in range(1,basamak):
    sonuc += 9*i*10**(i-1)
  sonuc+=(n-(10**(basamak-1)))*basamak
  return sonuc
digits(1020)