# -*- coding: utf-8 -*-
"""Convert_Seconds.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RGSR-WwoX6U4Z7XGtpYcyg8AMeCqJ0Fm

Given an integer n (in seconds), convert it into hours, minutes and seconds.
"""

def convert(seconds):
    seconds = seconds % (24 * 3600)
    hour = seconds // 3600
    seconds %= 3600
    minutes = seconds // 60
    seconds %= 60
      
    return "%d:%02d:%02d" % (hour, minutes, seconds)
      

n = 12345
print(convert(n))