# -*- coding: utf-8 -*-
"""isRotation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nlha_enHD0MiQzWjJzgXsmG7TRkVzXno
"""

This problem was asked by Google.
Given two strings A and B, return whether or not A can be shifted some number of times to get B.
For example, if A is abcde and B is cdeab, return true. If A is abc and B is acb, return false.

def isShifted(word1,word2):
  if word1 in 2*word2:
    return True
  else:
    return False

isShifted("abcde", "cdeab")