# -*- coding: utf-8 -*-
"""length_encoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O0CsegtIPgDowWGJMMsZrNu-3YqaA2mg
"""
"""
This is an interview question asked by Amazon.
Run-length encoding is a fast and simple method of encoding strings. The basic
idea is to represent repeated successive characters as a single count and 
character. For example, the string "AAAABBBCCDAA" would be encoded as "4A3B2C1D2A".
Implement run-length encoding and decoding. You can assume the string to be encoded
 have no digits and consists solely of alphabetic characters. You can assume the string to be decoded is valid.
"""
def encode(word):
  en_word=""
  new_dict ={}

  for i in word:
    if i not in new_dict:
      new_dict[i]=1
    else:
     new_dict[i]+=1
  for i in new_dict:
    en_word += str(new_dict[i])+str(i)
  return en_word

encode("AAABBCCCCDDDDDD")