# -*- coding: utf-8 -*-
"""median_of_sequence.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aMRYDy0Vat7D-Fz1C6JHbOG59ce52NV-
"""

sequence =[2,1,5,7,2,0,5]
new_list=[]

for i in sequence:
  new_list.append(i)
  x=sorted(new_list)
  n=len(new_list)
  
  if n%2 != 0:
    print(x[int((n+1)/2)-1])
  elif n%2 ==0:
     a=(x[int((n-1)/2)] + x[int(n / 2)])/2
     if int(a) == a:
       print(int(a))
     else:
       print(a)