# -*- coding: utf-8 -*-
"""obeb_ekok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GKGlTPyaaTv_1jS-MZi2xujdG99iY0IO
"""

sayi1 = int(input("Bir sayi girin: "))
sayi2 = int(input("Ýkinci saiyi girin: "))
 
OKEK = 0
OBEB = 0
k = 0
 
if sayi1 < sayi2:                   # büyük sayıyı al
    k = sayi2
else:
    k = sayi1 
 
while k <= sayi1 * sayi2:            # OKEK' i hesapla
    if k % sayi1 == 0 and k % sayi2 == 0:
         OKEK = k
         break                      # iki sayıyı çarp birbirlerine bölümü tam ise kır
    k = k +1
 
if sayi1 > sayi2:
    k = sayi2
else:
    k = sayi1                       # küçük sayıyı al
 
while k > 0:                        # OKEK' i hesapla
    if sayi1 % k == 0 and sayi2 % k == 0:
        OBEB = k
        break                       # iki sayıyı birbirine böl, bölüm sıfır ise kır
    k = k - 1
 
print('OBEB({}, {}):'.format(sayi1, sayi2), OBEB)
print('OKEK({}, {}):'.format(sayi1, sayi2), OKEK)