# -*- coding: utf-8 -*-
"""One-repeat_number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lm0j-y6ObyCncMk4PXimcVvAxO8q8o0Z
"""

Given an array of integers where every integer occurs three times except for one integer, 
which only occurs once, find and return the non-duplicated integer.
For example, given [6, 1, 3, 3, 3, 6, 6], return 1. Given [13, 19, 13, 13], return 19.

def find(liste):
  for i in liste:
    if liste.count(i) ==1:
      print(i)

find([6,6,1,3,3,3])