# -*- coding: utf-8 -*-
"""only_odd_or_even.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oytiPXETgER-ZlzJYxKoXG3U57lVzQ89
"""

[2, 4, 0, 100, 4, 11, 2602, 36]
Should return: 11 (the only odd number)
[160, 3, 1719, 19, 11, 13, -21]
Should return: 160 (the only even number)

list_1 =[2,4,0,100,4,11,2602,36]
list_2 =[160, 3, 1719, 19, 11, 13, -21]
odd_list=[]
even_list=[]

def say(a):
  for i in a:
    if i%2 ==0:
      even_list.append(i)
    else:
      odd_list.append(i)
  
  if len(odd_list)==1 and  len(even_list)> 1:
    print(odd_list)
  elif len(even_list)==1 and len(odd_list)> 1:
    print(even_list)

say(list_1)

list_1 =[2,4,0,100,4,11,2602,36]

even_list= [x for x in list_1 if x % 2==0]
odd_list=[x for x in list_1 if x % 2!=0]

if len(odd_list)==1 and  len(even_list)> 1:
    print(odd_list)
elif len(even_list)==1 and len(odd_list)> 1:
    print(even_list)