# -*- coding: utf-8 -*-
"""Palindrome.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UCKCjQL_6ae-K8rWwu_nNeLMhj1VC1kF
"""

#palindrome words
sentence = "madam"
if sentence==sentence[::-1]:
  print("true")
else:
  print("false")

s = "nurses run"
new_s ="".join(x for x in s if x.isalpha())
if new_s == n_s[::-1]:
  print("palindrome")
else:
  print("not palindrome")