# -*- coding: utf-8 -*-
"""perfect_numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dJlyEviRDYt9ybF2tlYObSPryqSEdpl8
"""

#perfect numbers

number = int(input("enter  integer number : "))
total =0
for i in range(1,number):
  if number % i ==0:
    total+=i
if number ==total:
  print("{} is perfect number".format(number))
else:
  print("{} is not perfect number".format(number))