# -*- coding: utf-8 -*-
"""power_set.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DZUh3fineG35qTxDXNB7IIoPgpVnZfiW
"""

def powerset(array):

  if array==[]:
    return False 
  else:
    power_set=[[]]
    for i in array:
      for j in power_set:
         
        power_set=power_set+[list(j)+[i]]
    return power_set

powerset({1,2,3})

array = {1,2,3}
power_set=[[]]
for i in array:
  #power_set.append([i])
  for j in power_set:
    power_set= power_set +  [list(j)+[i]]
print(power_set)

