# -*- coding: utf-8 -*-
"""reversed_sentence.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vbHpA7VKxpxSpnOLF0SXM_OVxRKq-3k2
"""

def reversed(sentence):
  new_s=sentence.split()
  print(*new_s[::-1])

reversed("hello word here")