# -*- coding: utf-8 -*-
"""samevowel_intersectionwords_0_larsona.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1niprbu_qCaqwaPnUjI8NU-SgwEcegdBN
"""

def same_vowel_group(liste):
  vowel="aeiou"
  sozluk={}
  ilk_kelime=set(i for i in liste[0] if i in vowel)
  for i in liste:
    if i not in sozluk:
      sozluk[i]=[]
    for k in i:
      if k in vowel and k not in sozluk[i]:
        sozluk[i].append(k)
  return [i for i in sozluk if set(sozluk[i])==ilk_kelime]   
same_vowel_group(["hoops", "chuff", "bot", "bottom"])

sentence1 = 'We are really pleased to meet you in our city'
sentence2 = 'The city was hit by a really heavy storm'

def solution(sentence1, sentence2):
    set1 = set(sentence1.split())
    set2 = set(sentence2.split())
    
    return sorted(list(set1^set2)), sorted(list(set1&set2)) # ^ A.symmetric_difference(B), & A.intersection(B)

print(solution(sentence1, sentence2))

array1 = [0,1,0,3,12]
array2 = [1,7,0,0,8,0,10,12,0,4]

def solution(nums):
    for i in nums:
        if 0 in nums:
            nums.remove(0)
            nums.append(0)
    print(nums)
    

solution(array1)
solution(array2)