# -*- coding: utf-8 -*-
"""FizzBuzz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/130zk_i13ShOAPBO_JRB_fON1U2cboS5t
"""

numbers=[]
for i in range (1,100):
  if i%3==0 and i%5==0:
    numbers.append("FizzBuzz")
  elif i%3==0:
    numbers.append("Fizz")
  elif i%5==0:
    numbers.append("Buzz")
  else:
    numbers.append(i)
print(numbers)