# -*- coding: utf-8 -*-
"""Leap_Year.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15X_IQmrE4yLiJR2fq4hrTbNirPdZ4bxM
"""

year = int(input("Enter the year : "))

if (year % 4) == 0:
   if (year % 100) == 0:
       if (year % 400) == 0:
           print("{0} is a leap year".format(year))
       else:
           print("{0} is not a leap year".format(year))
   else:
       print("{0} is a leap year".format(year))
else:
   print("{0} is not a leap year".format(year))