# -*- coding: utf-8 -*-
"""Letters_Count.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aRPBSS7qWijemHKtLfSf_N0v8G5tFZNU
"""

new_dict ={}
s = "hippo runs to us!"

for i in s:
  if i not in new_dict:
    new_dict[i]=1
  else:
    new_dict[i]+=1
print(new_dict)